// Mapa de palavras-chave -> emoji, usado para sugerir um emoji relacionado ao
// tema da categoria quando o admin não escolhe um manualmente (ex: ao
// importar 300 categorias em lote de uma vez, não dá pra escolher emoji uma
// por uma). Ordem importa: a primeira palavra-chave encontrada no nome
// (normalizado, sem acento) vence, então termos mais específicos vêm antes
// dos genéricos.
const KEYWORD_EMOJI: [string, string][] = [
  // comida e bebida
  ['pizza', '🍕'],
  ['hamburgu', '🍔'],
  ['hot dog', '🌭'],
  ['sushi', '🍣'],
  ['japones', '🍱'],
  ['churras', '🍖'],
  ['espetinho', '🍢'],
  ['esfiha', '🥙'],
  ['pastel', '🥟'],
  ['salgado', '🥐'],
  ['padaria', '🥖'],
  ['panifica', '🥖'],
  ['confeitaria', '🎂'],
  ['bolo', '🎂'],
  ['doce', '🍬'],
  ['brigadeiro', '🍬'],
  ['sorvet', '🍦'],
  ['acai', '🍧'],
  ['cafe', '☕'],
  ['cafeteria', '☕'],
  ['chocola', '🍫'],
  ['pao de mel', '🍯'],
  ['mel', '🍯'],
  ['churro', '🥨'],
  ['pipoca', '🍿'],
  ['algodao doce', '🍭'],
  ['petisc', '🍟'],
  ['lanchonete', '🍟'],
  ['restaurante', '🍽️'],
  ['marmita', '🍱'],
  ['comida', '🍽️'],
  ['buffet infantil', '🎈'],
  ['buffet', '🍽️'],
  ['cerveja', '🍺'],
  ['choperia', '🍺'],
  ['bar ', '🍻'],
  ['pub', '🍻'],
  ['bebida', '🥤'],
  ['sushiman', '🍣'],
  ['hortifruti', '🥦'],
  ['acougue', '🥩'],
  ['supermercado', '🛒'],
  ['mercado', '🛒'],
  ['conveniencia', '🏪'],
  ['adega', '🍷'],
  ['drink', '🍹'],
  ['bartender', '🍸'],

  // beleza e estética
  ['cabelei', '💇'],
  ['barbeir', '💈'],
  ['barbearia', '💈'],
  ['manicur', '💅'],
  ['unha', '💅'],
  ['nail', '💅'],
  ['micropigment', '💉'],
  ['sobrancel', '👁️'],
  ['maquia', '💄'],
  ['make', '💄'],
  ['depila', '🪒'],
  ['bronze', '🏖️'],
  ['estetic', '✨'],
  ['massoterap', '💆'],
  ['massag', '💆'],
  ['spa', '🧖'],
  ['salao de beleza', '💇'],
  ['trancista', '💇'],

  // saúde
  ['veterinar', '🐾'],
  ['petshop', '🐾'],
  ['pet shop', '🐾'],
  ['banho e tosa', '🐕'],
  ['tosador', '🐕'],
  ['clinica', '🏥'],
  ['medic', '⚕️'],
  ['dentist', '🦷'],
  ['odont', '🦷'],
  ['fisioterap', '🧑‍⚕️'],
  ['psicolog', '🧠'],
  ['psicopedagog', '🧠'],
  ['nutricion', '🥗'],
  ['farmac', '💊'],
  ['enfermeir', '⚕️'],
  ['fonoaudi', '🗣️'],
  ['podolog', '🦶'],
  ['acupuntur', '📍'],

  // moda e vestuário
  ['roupa', '👕'],
  ['moda', '👗'],
  ['calcado', '👟'],
  ['lingerie', '👙'],
  ['costurei', '🧵'],
  ['aviamento', '🧵'],
  ['tecido', '🧵'],
  ['joalheria', '💍'],
  ['semijoia', '💍'],
  ['bijuteria', '💍'],
  ['brecho', '👚'],
  ['bolsa', '👜'],
  ['otica', '👓'],
  ['oculos', '👓'],

  // casa e construção
  ['construcao', '🧱'],
  ['material de constru', '🧱'],
  ['pedreiro', '🧱'],
  ['reforma', '🔨'],
  ['eletricist', '🔌'],
  ['encanad', '🔧'],
  ['marcenaria', '🪚'],
  ['moveis', '🛋️'],
  ['movel', '🛋️'],
  ['vidra', '🪟'],
  ['serralher', '🔩'],
  ['pintor', '🎨'],
  ['gesseiro', '🧱'],
  ['azulej', '🧱'],
  ['jardin', '🌳'],
  ['paisagismo', '🌳'],
  ['limpeza', '🧹'],
  ['faxina', '🧹'],
  ['diarista', '🧹'],
  ['piscina', '🏊'],
  ['ar condicionado', '❄️'],

  // veículos
  ['auto ', '🚗'],
  ['automot', '🚗'],
  ['carro', '🚗'],
  ['mecanic', '🔧'],
  ['oficina', '🔧'],
  ['moto', '🏍️'],
  ['bicicleta', '🚲'],
  ['bicicletaria', '🚲'],
  ['borracharia', '🛞'],
  ['funilaria', '🚗'],
  ['lava car', '🚿'],
  ['posto de combustivel', '⛽'],
  ['revenda de veic', '🚗'],
  ['vistoria', '🚗'],
  ['transporte', '🚚'],
  ['motoboy', '🏍️'],
  ['motorista', '🚗'],
  ['guincho', '🚛'],
  ['reboque', '🚛'],

  // profissionais e serviços
  ['advogad', '⚖️'],
  ['advocacia', '⚖️'],
  ['contador', '📊'],
  ['contabil', '📊'],
  ['corretor de segur', '📄'],
  ['seguro', '📄'],
  ['imobiliar', '🏠'],
  ['arquitet', '📐'],
  ['engenhe', '📐'],
  ['despachante', '📋'],
  ['cartorio', '📜'],
  ['designer grafico', '🎨'],
  ['design de interiores', '🛋️'],
  ['fotograf', '📷'],
  ['videomaker', '🎥'],
  ['producao de video', '🎥'],
  ['editor de video', '🎬'],
  ['publicidade', '📣'],
  ['marketing', '📈'],
  ['agencia de viagens', '✈️'],
  ['guia de turismo', '🧭'],
  ['seguranca', '🛡️'],
  ['vigilante', '🛡️'],

  // eventos e entretenimento
  ['dj', '🎧'],
  ['banda', '🎸'],
  ['musica', '🎵'],
  ['cantor', '🎤'],
  ['locutor', '🎙️'],
  ['radio', '📻'],
  ['festa', '🎉'],
  ['decoraca', '🎈'],
  ['cerimonial', '💍'],
  ['casamento', '💍'],
  ['recread', '🎪'],
  ['animad', '🎪'],
  ['som para evento', '🔊'],
  ['podcast', '🎙️'],
  ['influenc', '📱'],
  ['danca', '💃'],
  ['dancarin', '💃'],

  // educação e infantil
  ['escola', '🏫'],
  ['faculdade', '🎓'],
  ['universidade', '🎓'],
  ['ingles', '🔤'],
  ['creche', '🧸'],
  ['infantil', '🧸'],
  ['baba', '🧸'],
  ['brinquedo', '🧸'],

  // pets e animais
  ['agropecuar', '🐄'],
  ['racao', '🐕'],

  // fitness e esporte
  ['academia', '💪'],
  ['crosstraining', '🏋️'],
  ['personal trainer', '🏋️'],
  ['pilates', '🧘'],
  ['ioga', '🧘'],
  ['natacao', '🏊'],
  ['futebol', '⚽'],
  ['judo', '🥋'],
  ['luta', '🥊'],
  ['beach tennis', '🎾'],
  ['atleta', '🏃'],
  ['treinador', '🏋️'],

  // outros comuns
  ['lava rapido', '🚿'],
  ['papelaria', '📎'],
  ['grafica', '🖨️'],
  ['presente', '🎁'],
  ['loja de canecas', '🎁'],
  ['artesanal', '🎨'],
  ['artesao', '🎨'],
  ['religios', '🙏'],
  ['tatuad', '🎨'],
  ['piercing', '💎'],
  ['instagram', '📱'],
  ['pagina de not', '📰'],
  ['portal de not', '📰'],
  ['sindicato', '🤝'],
  ['agencia bancaria', '🏦'],
  ['credito', '💳'],
  ['vendedor', '🛍️'],
  ['loja', '🛍️'],
];

export function guessCategoryEmoji(name: string): string {
  const normalized = name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase();

  for (const [keyword, emoji] of KEYWORD_EMOJI) {
    if (normalized.includes(keyword)) return emoji;
  }
  return '🏆';
}
